# Notebook for Capstone Project

**Garima Anand**

The notebook is will be used for the Capstone Project in the Coursera course

In [1]:
import pandas as pd
import numpy as np

In [2]:
!wget -O Data-Collisions.csv https://s3.us.cloud-object-storage.appdomain.cloud/cf-courses-data/CognitiveClass/DP0701EN/version-2/Data-Collisions.csv
df = pd.read_csv('Data-Collisions.csv',low_memory = False)

--2020-09-13 08:04:22--  https://s3.us.cloud-object-storage.appdomain.cloud/cf-courses-data/CognitiveClass/DP0701EN/version-2/Data-Collisions.csv
Resolving s3.us.cloud-object-storage.appdomain.cloud (s3.us.cloud-object-storage.appdomain.cloud)... 67.228.254.196
Connecting to s3.us.cloud-object-storage.appdomain.cloud (s3.us.cloud-object-storage.appdomain.cloud)|67.228.254.196|:443... connected.
HTTP request sent, awaiting response... 200 OK
Length: 73917638 (70M) [text/csv]
Saving to: ‘Data-Collisions.csv’

100%[======================================>] 73,917,638  44.3MB/s   in 1.6s   

2020-09-13 08:04:24 (44.3 MB/s) - ‘Data-Collisions.csv’ saved [73917638/73917638]



In [3]:
df.set_index('OBJECTID', inplace = True) 
dummy_variable = pd.get_dummies(df['SPEEDING'])
drop_labels = ['EXCEPTRSNCODE','SPEEDING','INCDTTM','SEVERITYCODE.1','EXCEPTRSNDESC','PEDROWNOTGRNT','SDOTCOLNUM','SDOT_COLCODE','INCKEY','COLDETKEY','PERSONCOUNT','PEDCOUNT','PEDCYLCOUNT','SEGLANEKEY','UNDERINFL','INATTENTIONIND','ST_COLCODE','SEGLANEKEY','INTKEY','CROSSWALKKEY','HITPARKEDCAR']
df.drop(drop_labels, axis=1, inplace=True)
df.shape

(194673, 17)

In [40]:
dummy_variable.rename(columns={'Y':'SPEEDING'}, inplace=True)
df = pd.concat([df, dummy_variable], axis=1)

df['INCDATE'] = pd.to_datetime(df['INCDATE'])

In [41]:
df_class_1 = df[df['SEVERITYCODE'] == 1]
df_class_2 = df[df['SEVERITYCODE'] == 2]

In [42]:
count_class1,count_class2 = df['SEVERITYCODE'].value_counts()
df_class_1_undersam = df_class_1.sample(count_class2)
df_undersam = pd.concat([df_class_1_undersam, df_class_2], axis=0)

count_class_under1,count_class_under2 = df_undersam['SEVERITYCODE'].value_counts()

print("1 after resampling: ", count_class_under1)
print("2 after resampling: ", count_class_under2)

1 after resampling:  58188
2 after resampling:  58188


In [43]:
df_undersam['WEATHER'].value_counts()

Clear                       67977
Raining                     20494
Overcast                    16865
Unknown                      6842
Snowing                       503
Other                         434
Fog/Smog/Smoke                359
Sleet/Hail/Freezing Rain       66
Blowing Sand/Dirt              32
Severe Crosswind               15
Partly Cloudy                   4
Name: WEATHER, dtype: int64

In [44]:
df_undersam['ROADCOND'].value_counts()

Dry               76076
Wet               29266
Unknown            6819
Ice                 690
Snow/Slush          561
Other                71
Standing Water       62
Sand/Mud/Dirt        46
Oil                  36
Name: ROADCOND, dtype: int64

## Extracting and processing the Weather feature

In [50]:
df_undersam = df_undersam.dropna(subset = ['X','Y'])
Feature1 = df_undersam[['X','Y']]
Feature1 = pd.concat([Feature1,pd.get_dummies(df_undersam['WEATHER'])], axis=1)
Feature1.drop(['Blowing Sand/Dirt','Fog/Smog/Smoke','Other','Partly Cloudy','Severe Crosswind','Sleet/Hail/Freezing Rain'],axis = 1, inplace = True)
X1 = Feature1

X          Y  Clear  Overcast  Raining  Snowing  Unknown
OBJECTID                                                                   
195691   -122.311826  47.596264      0         1        0        0        0
39885    -122.380415  47.570673      1         0        0        0        0
111363   -122.317302  47.601694      0         1        0        0        0
162468   -122.326329  47.688623      1         0        0        0        0
65202    -122.301470  47.546403      0         0        0        0        1
50561    -122.291030  47.540716      1         0        0        0        0
84265    -122.302770  47.608009      0         0        1        0        0
125056   -122.351973  47.690585      0         0        0        0        1
66665    -122.328880  47.734095      1         0        0        0        0
170919   -122.315567  47.593671      0         0        1        0        0
169512   -122.299963  47.603911      0         0        1        0        0
149114   -122.314992  47.596656      1         0        0        0        0
71279    -122.302218  47.594584      1         0        0        0        0
218306   -122.334211  47.609189      1         0        0        0        0
84396    -122.338430  47.625262      0         1        0        0        0
5181     -122.292785  47.560076      1         0        0        0        0
86939    -122.374857  47.663663      0         0        0        0        1
165335   -122.365754  47.660015      0         0        1        0        0
151937   -122.269990  47.530966      0         0        1        0        0
7926     -122.320790  47.614654      0         0        0        0        1
59821    -122.319684  47.626824      1         0        0        0        0
151661   -122.352133  47.625440      1         0        0        0        0
191748   -122.331073  47.615810      0         0        0        0        0
129506   -122.300094  47.549327      0         0        0        0        1
116193   -122.300645  47.673961      0         0        1        0        0
195670   -122.370766  47.664022      0         1        0        0        0
169249   -122.411979  47.578250      1         0        0        0        0
198330   -122.334276  47.734136      1         0        0        0        0
129368   -122.343532  47.629309      0         1        0        0        0
48758    -122.345881  47.692016      0         1        0        0        0
...              ...        ...    ...       ...      ...      ...      ...
219418   -122.290479  47.683048      1         0        0        0        0
219433   -122.313246  47.656834      0         0        1        0        0
219436   -122.320760  47.611169      1         0        0        0        0
219437   -122.333728  47.598291      0         0        1        0        0
219449   -122.322455  47.596670      1         0        0        0        0
219455   -122.338693  47.604652      1         0        0        0        0
219464   -122.373900  47.538295      0         0        1        0        0
219470   -122.316248  47.526445      0         0        1        0        0
219475   -122.382668  47.648457      1         0        0        0        0
219478   -122.387469  47.521817      1         0        0        0        0
219493   -122.355155  47.518279      0         0        1        0        0
219497   -122.349606  47.614031      0         0        0        0        0
219499   -122.345070  47.731674      1         0        0        0        0
219500   -122.334202  47.576652      0         1        0        0        0
219503   -122.353965  47.664306      1         0        0        0        0
219504   -122.289418  47.555133      0         0        1        0        0
219507   -122.322445  47.599186      0         1        0        0        0
219512   -122.328079  47.604161      1         0        0        0        0
219514   -122.355449  47.704720      0         0        1        0        0
219516   -122.302382  47.626759      1         0        0        0 

In [51]:
from sklearn import preprocessing
X1 = preprocessing.StandardScaler().fit(X1).transform(X1)
X1

/opt/conda/envs/Python36/lib/python3.6/site-packages/sklearn/preprocessing/data.py:645: DataConversionWarning: Data with input dtype uint8, float64 were all converted to float64 by StandardScaler.
  return self.partial_fit(X, y)
/opt/conda/envs/Python36/lib/python3.6/site-packages/ipykernel/__main__.py:2: DataConversionWarning: Data with input dtype uint8, float64 were all converted to float64 by StandardScaler.
  from ipykernel import kernelapp as app


array([[ 0.62062222, -0.41727561, -1.19533352, ..., -0.46005255,
        -0.06620081, -0.24289422],
       [-1.67805436, -0.86779125,  0.83658659, ..., -0.46005255,
        -0.06620081, -0.24289422],
       [ 0.43709407, -0.32168069, -1.19533352, ..., -0.46005255,
        -0.06620081, -0.24289422],
       ...,
       [ 1.32441493, -0.96046705,  0.83658659, ..., -0.46005255,
        -0.06620081, -0.24289422],
       [ 0.79280597,  1.11046679,  0.83658659, ..., -0.46005255,
        -0.06620081, -0.24289422],
       [-0.83690543,  1.03454559,  0.83658659, ..., -0.46005255,
        -0.06620081, -0.24289422]])

In [25]:
y = df_undersam['SEVERITYCODE'].values
y.shape

(113505,)

In [26]:
#Splitting the data into train and test data
from sklearn.model_selection import train_test_split
X1_train, X1_test, y1_train, y1_test = train_test_split(X1, y, test_size=0.2)
print ('Train set:', X1_train.shape,  y1_train.shape)
print ('Test set:', X1_test.shape,  y1_test.shape)

Train set: (90804, 13) (90804,)
Test set: (22701, 13) (22701,)


## Model Development for Weather Feature

### K Nearest Neighbor (KNN) for Weather feature

In [27]:
from sklearn.neighbors import KNeighborsClassifier

In [101]:
# Finding the best k for the model
Ks=15
mean_acc=np.zeros((Ks-1))
std_acc=np.zeros((Ks-1))
for n in range(1,Ks):
    
    #Train Model and Predict  
    kNN_model = KNeighborsClassifier(n_neighbors=n).fit(X1_train,y1_train)
    yhat = kNN_model.predict(X1_test)
    mean_acc[n-1]=np.mean(yhat==y1_test);
    std_acc[n-1]=np.std(yhat==y1_test)/np.sqrt(yhat.shape[0])
mean_acc

array([0.55686618, 0.54513623, 0.5637816 , 0.55305832, 0.56340956,
       0.55491848, 0.56651712, 0.55846373, 0.56546668, 0.56067403,
       0.5647445 , 0.56159317, 0.56305942, 0.55990809])

In [52]:
from sklearn import metrics
#creating the model again but with the best k value determined previously
k = 3
#Train Model and Predict  
neigh1 = KNeighborsClassifier(n_neighbors = k).fit(X1_train,y1_train)
yhat_test = neigh1.predict(X1_test)

print("Test set Accuracy: ", metrics.accuracy_score(y1_test, yhat_test))
print("The best k value for the model is", 3 ,"with accuracy of", mean_acc.max())

Test set Accuracy:  0.5616933174750011


NameError: name 'mean_acc' is not defined

### Decision Tree for Weather Feature

In [63]:
from sklearn.tree import DecisionTreeClassifier
Ks = 10
mean_acc1 = np.zeros((Ks-1))
for n in range(1,Ks):
    #Train Model and Predict  
    tree_define = DecisionTreeClassifier(criterion="entropy", max_depth = n).fit(X1_train,y1_train)
    y_hat2 = tree_define.predict(X1_test)
    mean_acc1[n-1]=np.mean(y_hat2==y1_test);
mean_acc1

array([0.54415144, 0.54415144, 0.54526753, 0.54520188, 0.53977459,
       0.54870336, 0.54410767, 0.5469745 , 0.54835321])

In [160]:
k = 6
tree_define1 = DecisionTreeClassifier(criterion="entropy", max_depth = k)
tree_define1.fit(X1_train,y1_train)
yhat_test2 = tree_define1.predict(X1_test)

print("Test set Accuracy: ", metrics.accuracy_score(y1_test, yhat_test2))

Test set Accuracy:  0.5462085567348726


### Logistic Regression for Weather Feature

In [161]:
from sklearn.linear_model import LogisticRegression
from sklearn.metrics import log_loss
LR1 = LogisticRegression(C=0.1, solver='liblinear').fit(X1_train,y1_train)
yhat_test3 = LR1.predict(X1_test)
yhat_prob = LR1.predict_proba(X1_test) 
print("LogLoss: : %.5f" % log_loss(y1_test, yhat_prob)) 

LogLoss: : 0.67225


In [162]:
print("Using logistic regression and changing the regulization parameter, the best C value is", 0.1, "with the log loss of %.5f" % log_loss(y1_test, yhat_prob))

Using logistic regression and changing the regulization parameter, the best C value is 0.1 with the log loss of 0.67225


## Extracting and processing the road condition feature

In [122]:
Feature2 = df_undersam[['X','Y']]
Feature2 = pd.concat([Feature2,pd.get_dummies(df_undersam['ROADCOND'])], axis=1)
Feature2.drop(['Oil','Other','Snow/Slush','Sand/Mud/Dirt','Standing Water'], axis = 1,inplace=True)
X2 = Feature2


X          Y  Dry  Ice  Unknown  Wet
OBJECTID                                               
63492    -122.328435  47.682254    1    0        0    0
178631   -122.352732  47.702178    1    0        0    0
35823    -122.324714  47.686786    0    0        0    1
120233   -122.294581  47.717376    1    0        0    0
82655    -122.366185  47.661826    1    0        0    0

In [123]:
X2 = preprocessing.StandardScaler().fit(X2).transform(X2)
X2.shape

/opt/conda/envs/Python36/lib/python3.6/site-packages/sklearn/preprocessing/data.py:645: DataConversionWarning: Data with input dtype uint8, float64 were all converted to float64 by StandardScaler.
  return self.partial_fit(X, y)
/opt/conda/envs/Python36/lib/python3.6/site-packages/ipykernel/__main__.py:1: DataConversionWarning: Data with input dtype uint8, float64 were all converted to float64 by StandardScaler.
  if __name__ == '__main__':


(114236, 6)

In [124]:
y = df_undersam['SEVERITYCODE'].values
y.shape

(114236,)

In [128]:
X2_train, X2_test, y2_train, y2_test = train_test_split(X2, y, test_size=0.2)
print ('Train set:', X2_train.shape,  y2_train.shape)
print ('Test set:', X2_test.shape,  y2_test.shape)

Train set: (91388, 6) (91388,)
Test set: (22848, 6) (22848,)


## Model Development for Road condition Feature

### K Nearest Neighbor for Road condition feature

In [129]:
from sklearn.neighbors import KNeighborsClassifier

In [163]:
# Finding the best k for the model
Ks=15
mean_acc=np.zeros((Ks-1))
std_acc=np.zeros((Ks-1))
for n in range(1,Ks):
    
    #Train Model and Predict  
    kNN_model = KNeighborsClassifier(n_neighbors=n).fit(X2_train,y2_train)
    yhat = kNN_model.predict(X2_test)
    mean_acc[n-1]=np.mean(yhat==y2_test);
    std_acc[n-1]=np.std(yhat==y2_test)/np.sqrt(yhat.shape[0])
mean_acc

KeyboardInterrupt: 

In [164]:
from sklearn import metrics
#creating the model again but with the best k value determined previously
k = 13
#Train Model and Predict  
neigh2 = KNeighborsClassifier(n_neighbors = k).fit(X2_train,y2_train)
yhat_test = neigh2.predict(X2_test)

print("Test set Accuracy: ", metrics.accuracy_score(y2_test, yhat_test))
print("The best k value for the model is", k ,"with accuracy of", mean_acc.max())

Test set Accuracy:  0.5841211484593838
The best k value for the model is 13 with accuracy of 0.0


### Decision Tree for Road condition feature

In [133]:
from sklearn.tree import DecisionTreeClassifier
Ks = 10
mean_acc1 = np.zeros((Ks-1))
for n in range(1,Ks):
    #Train Model and Predict  
    tree_define = DecisionTreeClassifier(criterion="entropy", max_depth = n).fit(X2_train,y2_train)
    y_hat2 = tree_define.predict(X2_test)
    mean_acc1[n-1]=np.mean(y_hat2==y2_test);
mean_acc1

array([0.55033263, 0.55033263, 0.55273985, 0.55282738, 0.55287115,
       0.55208333, 0.55904237, 0.55768557, 0.5537465 ])

In [165]:
k = 7
tree_define2 = DecisionTreeClassifier(criterion="entropy", max_depth = k)
tree_define2.fit(X2_train,y2_train)
yhat_test2 = tree_define2.predict(X2_test)

print("Test set Accuracy: ", metrics.accuracy_score(y2_test, yhat_test2))

Test set Accuracy:  0.5590423669467787


### Logistic Regression for Road condition feature

In [166]:
from sklearn.linear_model import LogisticRegression
from sklearn.metrics import log_loss
LR2 = LogisticRegression(C=0.2, solver='liblinear').fit(X2_train,y2_train)
yhat_test3 = LR2.predict(X2_test)
yhat_prob = LR2.predict_proba(X2_test) 
print("LogLoss: : %.5f" % log_loss(y2_test, yhat_prob)) 

LogLoss: : 0.67110


In [149]:
print("Using logistic regression and changing the regulization parameter, the best C value is", 0.2, "with the log loss of %.5f" % log_loss(y2_test, yhat_prob))

Using logistic regression and changing the regulization parameter, the best C value is 0.2 with the log loss of 0.67110


## Model Evaluation for Features

In [169]:
from sklearn.metrics import jaccard_similarity_score
from sklearn.metrics import f1_score
from sklearn.metrics import log_loss

### Evaluation for models using Weather feature

In [167]:
yhat_test1 = neigh1.predict(X1_test)
yhat_test2 = tree_define1.predict(X1_test)
yhat_test3 = LR1.predict(X1_test)

In [170]:
#Jaccard Evaluation
KNN_jac1 = jaccard_similarity_score(y1_test, yhat_test1);
DT_jac1 = jaccard_similarity_score(y1_test, yhat_test2);
LR_jac1 = jaccard_similarity_score(y1_test, yhat_test3);

In [171]:
#F1-Score
KNN_sc1 = f1_score(y1_test, yhat_test1, average='weighted')
DT_sc1 = f1_score(y1_test, yhat_test2, average='weighted')
LR_sc1 = f1_score(y1_test, yhat_test3, average='weighted')

In [172]:
#LogLoss
yhat_prob1 = LR1.predict_proba(X1_test)
logloss1 = log_loss(y1_test,yhat_prob1)

In [200]:
labels = ['Algorithm','Jaccard','F1-Score','LogLoss']
report1 = pd.DataFrame(data=[['KNN',KNN_jac1,KNN_sc1,'NA'],['Decision Tree',DT_jac1,DT_sc1,'NA'],['LogisticRegression',LR_jac1,LR_sc1,logloss1]], columns = labels)
report1.set_index('Algorithm', inplace = True) 
report1


Jaccard  F1-Score   LogLoss
Algorithm                                       
KNN                 0.563782  0.563638        NA
Decision Tree       0.546209  0.543917        NA
LogisticRegression  0.548922  0.494079  0.672254

### Evaluation for models using Road condition feature

In [201]:
yhat_test12 = neigh2.predict(X2_test)
yhat_test22 = tree_define2.predict(X2_test)
yhat_test32 = LR2.predict(X2_test)

In [202]:
#Jaccard Evaluation
KNN_jac2 = jaccard_similarity_score(y2_test, yhat_test12);
DT_jac2 = jaccard_similarity_score(y2_test, yhat_test22);
LR_jac2 = jaccard_similarity_score(y2_test, yhat_test32);

In [203]:
#F1-Score
KNN_sc2 = f1_score(y2_test, yhat_test12, average='weighted')
DT_sc2 = f1_score(y2_test, yhat_test22, average='weighted')
LR_sc2 = f1_score(y2_test, yhat_test32, average='weighted')

In [204]:
#LogLoss
yhat_prob2 = LR2.predict_proba(X2_test)
logloss2 = log_loss(y2_test,yhat_prob2)

In [205]:
labels = ['Algorithm','Jaccard','F1-Score','LogLoss']
report2 = pd.DataFrame(data=[['KNN',KNN_jac2,KNN_sc2,'NA'],['Decision Tree',DT_jac2,DT_sc2,'NA'],['LogisticRegression',LR_jac2,LR_sc2,logloss2]], columns = labels)
report2.set_index('Algorithm', inplace = True) 
report2

Jaccard  F1-Score   LogLoss
Algorithm                                       
KNN                 0.584121  0.582869        NA
Decision Tree       0.559042  0.492537        NA
LogisticRegression  0.556416  0.494928  0.671102

## Map of collisions

In [206]:
!pip install folium
import folium

     |████████████████████████████████| 102kB 8.6MB/s ta 0:00:011


In [207]:
seattle_loc = [47.6062, -122.3321]
map_seattle = folium.Map(location=seattle_loc, zoom_start=12)
folium.Marker(seattle_loc).add_to(map_seattle)

df_collisions = df.iloc[0:100, :]

# instantiate a feature group for the incidents in the dataframe
collision = folium.map.FeatureGroup()

# loop through the 100 crimes and add each to the incidents feature group
for lat, lng, in zip(df_collisions.Y, df_collisions.X):
    collision.add_child(
        folium.CircleMarker([lat, lng],radius=5,color='red')
    )

# add incidents to map
map_seattle.add_child(collision)
#map_seattle = folium.Map()